// Auto-generated GPU lib_exec for MOD_NAME
// Include inside GpuRuntime class body
// This file is autogenerated - do not edit manually.

HSHM_GPU_FUN void Run(chi::u32 method, hipc::FullPtr<chi::Task> task_ptr,
                       chi::gpu::GpuRunContext &rctx) override {
  switch (method) {
    case Method::kGpuSubmit: {
      auto typed = task_ptr.template Cast<GpuSubmitTask>();
      GpuSubmit(typed, rctx);
      break;
    }
    default: break;
  }
}

HSHM_GPU_FUN hipc::FullPtr<chi::Task> LocalAllocLoadTask(
    chi::u32 method, chi::LocalLoadTaskArchive &archive) override {
  switch (method) {
    case Method::kGpuSubmit: {
      auto *alloc = gpu_alloc_;
      auto task = alloc->template AllocateObjs<GpuSubmitTask>(1);
      if (task.IsNull()) return hipc::FullPtr<chi::Task>::GetNull();
      new (task.ptr_) GpuSubmitTask();
      archive.SetMsgType(chi::LocalMsgType::kSerializeIn);
      task.ptr_->SerializeIn(archive);
      return task.template Cast<chi::Task>();
    }
    default: return hipc::FullPtr<chi::Task>::GetNull();
  }
}

HSHM_GPU_FUN void LocalSaveTask(
    chi::u32 method, chi::LocalSaveTaskArchive &archive,
    const hipc::FullPtr<chi::Task> &task) override {
  switch (method) {
    case Method::kGpuSubmit: {
      auto typed = task.template Cast<GpuSubmitTask>();
      typed->SerializeOut(archive);
      break;
    }
    default: break;
  }
}
